# Generated by Django 4.1.3 on 2022-11-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
